// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimatedIcon: typeof import('./src/components/AnimatedIcon.vue')['default']
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    AssetsCard: typeof import('./src/components/cards/AssetsCard.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    AuthLogo: typeof import('./src/components/AuthLogo.vue')['default']
    Breadcrumb: typeof import('./src/components/breadcrumb.vue')['default']
    CommaNum: typeof import('./src/components/partials/CommaNum.vue')['default']
    ConfirmModal: typeof import('./src/components/modals/ConfirmModal.vue')['default']
    DFeild: typeof import('./src/components/partials/DFeild.vue')['default']
    ExchangeCard: typeof import('./src/components/cards/ExchangeCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeSliders: typeof import('./src/components/HomeSliders.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InviteCard: typeof import('./src/components/cards/InviteCard.vue')['default']
    LastOrders: typeof import('./src/components/cards/LastOrders.vue')['default']
    LastStakes: typeof import('./src/components/cards/LastStakes.vue')['default']
    PageFooter: typeof import('./src/components/common/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    ReferralListTree: typeof import('./src/components/ReferralListTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StakeCard: typeof import('./src/components/cards/StakeCard.vue')['default']
    StakeDetails: typeof import('./src/components/StakeDetails.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserWallets: typeof import('./src/components/modals/UserWallets.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
